// default package
// Generated 14-dic-2016 13:35:27 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Boletos generated by hbm2java
 */
@Entity
@Table(name = "Boletos", schema = "dbo")
public class Boletos implements java.io.Serializable {

	private BoletosId id;
	private Sorteos sorteos;
	private byte reintegro;
	private byte tipoApuesta;
	private Byte numeroAcertados;
	private BigDecimal premio;
	private Set<NumerosBoletos> numerosBoletoses = new HashSet<NumerosBoletos>(0);

	public Boletos() {
	}

	public Boletos(BoletosId id, Sorteos sorteos, byte reintegro, byte tipoApuesta) {
		this.id = id;
		this.sorteos = sorteos;
		this.reintegro = reintegro;
		this.tipoApuesta = tipoApuesta;
	}

	public Boletos(BoletosId id, Sorteos sorteos, byte reintegro, byte tipoApuesta, Byte numeroAcertados,
			BigDecimal premio, Set<NumerosBoletos> numerosBoletoses) {
		this.id = id;
		this.sorteos = sorteos;
		this.reintegro = reintegro;
		this.tipoApuesta = tipoApuesta;
		this.numeroAcertados = numeroAcertados;
		this.premio = premio;
		this.numerosBoletoses = numerosBoletoses;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idBoleto", column = @Column(name = "IdBoleto", nullable = false)),
			@AttributeOverride(name = "idSorteo", column = @Column(name = "IdSorteo", nullable = false)) })
	public BoletosId getId() {
		return this.id;
	}

	public void setId(BoletosId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdSorteo", nullable = false, insertable = false, updatable = false)
	public Sorteos getSorteos() {
		return this.sorteos;
	}

	public void setSorteos(Sorteos sorteos) {
		this.sorteos = sorteos;
	}

	@Column(name = "Reintegro", nullable = false)
	public byte getReintegro() {
		return this.reintegro;
	}

	public void setReintegro(byte reintegro) {
		this.reintegro = reintegro;
	}

	@Column(name = "TipoApuesta", nullable = false)
	public byte getTipoApuesta() {
		return this.tipoApuesta;
	}

	public void setTipoApuesta(byte tipoApuesta) {
		this.tipoApuesta = tipoApuesta;
	}

	@Column(name = "NumeroAcertados")
	public Byte getNumeroAcertados() {
		return this.numeroAcertados;
	}

	public void setNumeroAcertados(Byte numeroAcertados) {
		this.numeroAcertados = numeroAcertados;
	}

	@Column(name = "Premio", scale = 4)
	public BigDecimal getPremio() {
		return this.premio;
	}

	public void setPremio(BigDecimal premio) {
		this.premio = premio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "boletos")
	public Set<NumerosBoletos> getNumerosBoletoses() {
		return this.numerosBoletoses;
	}

	public void setNumerosBoletoses(Set<NumerosBoletos> numerosBoletoses) {
		this.numerosBoletoses = numerosBoletoses;
	}

}
