// default package
// Generated 19-dic-2016 9:00:20 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NumerosBoletos generated by hbm2java
 */
@Entity
@Table(name = "NumerosBoletos", schema = "dbo")
public class NumerosBoletos implements java.io.Serializable {

	private NumerosBoletosId id;
	private Boletos boletos;

	public NumerosBoletos() {
	}

	public NumerosBoletos(NumerosBoletosId id, Boletos boletos) {
		this.id = id;
		this.boletos = boletos;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idSorteo", column = @Column(name = "IdSorteo", nullable = false)),
			@AttributeOverride(name = "idBoleto", column = @Column(name = "IdBoleto", nullable = false)),
			@AttributeOverride(name = "numero", column = @Column(name = "Numero", nullable = false)) })
	public NumerosBoletosId getId() {
		return this.id;
	}

	public void setId(NumerosBoletosId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "IdBoleto", referencedColumnName = "IdBoleto", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "IdSorteo", referencedColumnName = "IdSorteo", nullable = false, insertable = false, updatable = false) })
	public Boletos getBoletos() {
		return this.boletos;
	}

	public void setBoletos(Boletos boletos) {
		this.boletos = boletos;
	}

}
