// default package
// Generated 19-dic-2016 9:00:20 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PremiosId generated by hbm2java
 */
@Embeddable
public class PremiosId implements java.io.Serializable {

	private byte tipoApuesta;
	private byte numerosAcertados;

	public PremiosId() {
	}

	public PremiosId(byte tipoApuesta, byte numerosAcertados) {
		this.tipoApuesta = tipoApuesta;
		this.numerosAcertados = numerosAcertados;
	}

	@Column(name = "TipoApuesta", nullable = false)
	public byte getTipoApuesta() {
		return this.tipoApuesta;
	}

	public void setTipoApuesta(byte tipoApuesta) {
		this.tipoApuesta = tipoApuesta;
	}

	@Column(name = "NumerosAcertados", nullable = false)
	public byte getNumerosAcertados() {
		return this.numerosAcertados;
	}

	public void setNumerosAcertados(byte numerosAcertados) {
		this.numerosAcertados = numerosAcertados;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PremiosId))
			return false;
		PremiosId castOther = (PremiosId) other;

		return (this.getTipoApuesta() == castOther.getTipoApuesta())
				&& (this.getNumerosAcertados() == castOther.getNumerosAcertados());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTipoApuesta();
		result = 37 * result + this.getNumerosAcertados();
		return result;
	}

}
