// default package
// Generated 14-dic-2016 13:35:27 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sorteos generated by hbm2java
 */
@Entity
@Table(name = "Sorteos", schema = "dbo")
public class Sorteos implements java.io.Serializable {

	private long idSorteo;
	private Date fechaSorteo;
	private Byte num1;
	private Byte num2;
	private Byte num3;
	private Byte num4;
	private Byte num5;
	private Byte num6;
	private Byte comp;
	private Byte rein;
	private Set<Boletos> boletoses = new HashSet<Boletos>(0);

	public Sorteos() {
	}

	public Sorteos(long idSorteo, Date fechaSorteo) {
		this.idSorteo = idSorteo;
		this.fechaSorteo = fechaSorteo;
	}

	public Sorteos(long idSorteo, Date fechaSorteo, Byte num1, Byte num2, Byte num3, Byte num4, Byte num5, Byte num6,
			Byte comp, Byte rein, Set<Boletos> boletoses) {
		this.idSorteo = idSorteo;
		this.fechaSorteo = fechaSorteo;
		this.num1 = num1;
		this.num2 = num2;
		this.num3 = num3;
		this.num4 = num4;
		this.num5 = num5;
		this.num6 = num6;
		this.comp = comp;
		this.rein = rein;
		this.boletoses = boletoses;
	}

	@Id

	@Column(name = "IdSorteo", unique = true, nullable = false)
	public long getIdSorteo() {
		return this.idSorteo;
	}

	public void setIdSorteo(long idSorteo) {
		this.idSorteo = idSorteo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaSorteo", nullable = false, length = 16)
	public Date getFechaSorteo() {
		return this.fechaSorteo;
	}

	public void setFechaSorteo(Date fechaSorteo) {
		this.fechaSorteo = fechaSorteo;
	}

	@Column(name = "num1")
	public Byte getNum1() {
		return this.num1;
	}

	public void setNum1(Byte num1) {
		this.num1 = num1;
	}

	@Column(name = "num2")
	public Byte getNum2() {
		return this.num2;
	}

	public void setNum2(Byte num2) {
		this.num2 = num2;
	}

	@Column(name = "num3")
	public Byte getNum3() {
		return this.num3;
	}

	public void setNum3(Byte num3) {
		this.num3 = num3;
	}

	@Column(name = "num4")
	public Byte getNum4() {
		return this.num4;
	}

	public void setNum4(Byte num4) {
		this.num4 = num4;
	}

	@Column(name = "num5")
	public Byte getNum5() {
		return this.num5;
	}

	public void setNum5(Byte num5) {
		this.num5 = num5;
	}

	@Column(name = "num6")
	public Byte getNum6() {
		return this.num6;
	}

	public void setNum6(Byte num6) {
		this.num6 = num6;
	}

	@Column(name = "comp")
	public Byte getComp() {
		return this.comp;
	}

	public void setComp(Byte comp) {
		this.comp = comp;
	}

	@Column(name = "rein")
	public Byte getRein() {
		return this.rein;
	}

	public void setRein(Byte rein) {
		this.rein = rein;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sorteos")
	public Set<Boletos> getBoletoses() {
		return this.boletoses;
	}

	public void setBoletoses(Set<Boletos> boletoses) {
		this.boletoses = boletoses;
	}

}
